# Generated by Django 4.2.6 on 2023-10-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contactmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
