# Generated by Django 4.2.6 on 2023-10-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
            preserve_default=False,
        ),
    ]
